#qdrant:
#  url: "https://8e1429f5-4eb0-4839-8273-af4b823b93dd.us-east4-0.gcp.cloud.qdrant.io:6333"
#  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.9PNh2uMOZeVlGDG-FZ6GDdq_SajIsZeGmBpxHUpYL2o"
#  collection_name: "eventa_document_embeddings_collection"
qdrant:
  url: http://localhost:6333
  api_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.9PNh2uMOZeVlGDG-FZ6GDdq_SajIsZeGmBpxHUpYL2o"
  collection_name: "eventa_document_embeddings_collection"
params:
  prefetch_limit: 5000
  search_limit: 10
