# processor:
#   name: "/home/totuanan/Workplace/eventa_lastsong/opensource/colpali/checkpoints/checkpoint-10000"
# model:
#   name: "/home/totuanan/Workplace/eventa_lastsong/opensource/colpali/checkpoints/checkpoint-10000"

processor:
 name: "vidore/colqwen2.5-v0.2"
model:
 name: "vidore/colqwen2.5-v0.2"
